[build-system]
requires = ["setuptools>=65.0.0", "wheel>=0.38.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sprov-ai-api"
version = "1.0.0"
description = "Sprov AI Audio Analysis API"
requires-python = ">=3.11" 