services:
  - type: web
    name: sprov-ai-api
    env: python
    pythonVersion: "3.11"
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.main_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 