services:
  - type: web
    name: sprov-ai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false 